### ISSUE TITLE
Literally unusable (on browser)

### ISSUE THREAD

**Issue by grvcoelho** [otaviopace/gargula#1]
Hi, I'm trying to use this project in the browser, but I just can't :confused:

**Comment by evaporei** [comment]
If anyone can make this work on browser, it would be awesome!

**Comment by aamay001** [comment]
Hi,

Do you want this to be served and rendered by node or do you want a static HTML page?

I can do either.

**Comment by evaporei** [comment]
Sorry @aamay001 , @grvcoelho already done it! There is another `hacktoberfest` issue on this project, you can check it out though! :slightly_smiling_face:

**Comment by aamay001** [comment]
No problem! @otaviopace  I will take a look...
