### ISSUE TITLE
Change from node to JavaScript on Readme

### ISSUE THREAD

**Issue by evaporei** [otaviopace/gargula#3]
On the `README.md` file of the project there is the phrase:

```
A node package for printing the infamous gargoyle or gargula in portuguese
```

However now the project accepts to be used on the browser too.
The `node` word should be substituted with `JavaScript`.

**Bonus**: somehow add to the `README.md` a description informing that this package can be used both on `Node.js` and on the Browser. The idea is to show somehow what platforms it supports.

**Comment by sagarchoudhary96** [comment]
@otaviopace  ican do that
